# This is a sample build configuration for Javascript (Node.js).
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  branches:  # Pipelines that run automatically on a commit to a branch
    development:
      - step:
          script: # Modify the commands below to build your repository.
            - mkdir -p ~/.ssh
            - cat my_known_hosts >> ~/.ssh/known_hosts
            - (umask 077; echo $MY_SSH_KEY | base64 --decode > ~/.ssh/id_rsa)
            - npm install
            - NODE_ENV=prod npm run build
            - cp -R configuration/users/templates dist/configuration/users
            - cp -R resources dist
            - mv dist webapp-backend && tar cvfz webapp-backend.tgz webapp-backend
            - scp webapp-backend.tgz ubuntu@dev.kpibi.com:./apps/uploads
            - ssh ubuntu@dev.kpibi.com 'cd apps/uploads && tar xvfz webapp-backend.tgz && cp -R webapp-backend/* ../webapp-backend && rm -Rf webapp-backend* && cd ../webapp-backend && npm install && pm2 restart webapp-backend'

